### ISSUE TITLE
store/initialState import causes circular dependency

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#784]
**shresthabijay**
I ran into some sort of circular dependency issue. It goes away on importing `store` in `setupTests.js`. We don't this in `dev` because we import `App` inside `setupTests.js` which loads `store` before any `utils` have been imported directly from `./util/index.js`.

Import any `util` function before `App` is imported in `setupTest.js` in `dev`. Then run some tests. You will get this error.

```js
TypeError: Cannot read property 'parseJsonSafe' of undefined

      at Object.get [as parseJsonSafe] (src/util/index.ts:387:27)
      at initialState (src/util/initialState.ts:107:20)
      at appReducer (src/reducers/app.ts:8:36)
      at dispatch (node_modules/redux/lib/redux.js:219:22)
      at createStore (node_modules/redux/lib/redux.js:305:3)
      at node_modules/redux/lib/redux.js:635:31
      at createStore (node_modules/redux/lib/redux.js:85:33)
      at Object.<anonymous> (src/store.js:14:22)
      at Object.<anonymous> (src/selectors/canShowModal.ts:1:1)
      at Object.<anonymous> (src/selectors/index.ts:4:1)
      at Object.<anonymous> (src/util/addThought.ts:3:1)
      at Object.<anonymous> (src/util/index.ts:3:1)
      at Object.<anonymous> (src/util/__tests__/splice.js:1:1)
```

I think this a circular dependency error because some `utils` like `addThought` import some `selectors`. It causes all the `selectors` to load. Since `selectors` use `utils` too it causes this error.  Since `store` somewhere in it's dependency tree imports a util `initialState` directly from it's file `./util/initialState` instead from `./util/index.js`, it resolves this issue. It pretty confusing. Have you encountered this before ?

**raineorshine**
The reason is fails on `parseJsonSafe` is because it is the [first util function that is called in `initialState`](https://github.com/cybersemics/em/blob/dev/src/util/initialState.ts#L107). Importing and using `initialState` in the main [appReducer](https://github.com/cybersemics/em/blob/dev/src/reducers/app.ts#L8) is where the entry point seems to be. If you remove `initialState` there, the error goes away.

Importing `store` in `canShowModal` was also causing problems, which I fixed.

Importing the util functions individually, and thus not importing the util index file, seems to fix the issue. It's preferable to importing `store` in `setupTests`, but it still feels like a hack. I wonder if extricating the global `store` from other util functions might get closer to the root of the issue.

**Comment by raineorshine** [comment]
`raw.macro` was probably the culprit. Fixed in 9088d6465093c37899658d43889d874f4161e41c.
